# Generated by Django 4.1.3 on 2022-12-22 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applocal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactoform',
            old_name='email',
            new_name='emailcontacto',
        ),
        migrations.RenameField(
            model_name='contactoform',
            old_name='mensaje',
            new_name='mensajecontacto',
        ),
        migrations.RenameField(
            model_name='contactoform',
            old_name='nombre',
            new_name='nombrecontacto',
        ),
        migrations.RenameField(
            model_name='contactoform',
            old_name='numero_telefono',
            new_name='telefonocontacto',
        ),
    ]
