# Generated by Django 4.1.3 on 2022-12-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applocal', '0002_rename_email_contactoform_emailcontacto_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactoForm',
            new_name='contactomodel',
        ),
    ]
