# Generated by Django 4.1.3 on 2023-01-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applocal', '0004_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=150)),
                ('cuerpo', models.TextField()),
                ('imagen', models.ImageField(upload_to='imagenesPost')),
                ('autor', models.CharField(max_length=50)),
                ('fecha', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
