# Generated by Django 4.1.3 on 2023-01-09 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applocal', '0005_blogmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='imagen',
        ),
    ]
